name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set env RELEASE_VERSION
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag asanrom/eidas-node:latest

    - name: Docker Login (GitHub Packages)
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag version (GitHub Packages)
      run: docker tag asanrom/eidas-node:latest ghcr.io/agustinsrg/eidas-node:${{ env.RELEASE_VERSION }}

    - name: Tag latest (GitHub Packages)
      run: docker tag asanrom/eidas-node:latest ghcr.io/agustinsrg/eidas-node:latest

    - name: Push the Docker image (GitHub Packages) (Current Version)
      run: docker push ghcr.io/agustinsrg/eidas-node:${{ env.RELEASE_VERSION }}
        
    - name: Push the Docker image (GitHub Packages) (Latest)
      run: docker push ghcr.io/agustinsrg/rtmp-server:latest
    
